import '../../Habilidade/habilidade.dart';
import '../../Idioma/index.dart';
import '../../Personagem/index.dart';
import '../index.dart';

class MeioElfos extends Raca {
  Idioma? _idiomaI;
  ValorHabilidade? _valorHabilidadeI;
  ValorHabilidade? _valorHabilidadeII;
  Pericia? _periciaI;
  Pericia? _periciaII;

  MeioElfos({
    Idioma? idiomaI,
    ValorHabilidade? valorHabilidadeI,
    ValorHabilidade? valorHabilidadeII,
    Pericia? periciaI,
    Pericia? periciaII,
  }) : super(
          //Atribuindo
          categoriaTamanho: CategoriaTamanho.Medio,
          descricao:
              "Meio-elfos não possuem terra própria, no entanto, eles são bem-vindos em cidades humanas e um pouco menos bem recebidos em florestas élficas. Em cidades grandes, em regiões em que elfos e humanos costumam interagir, meio-elfos podem ser numerosos o suficiente para formar pequenas comunidades entre eles. Eles gostam da companhia de outros meio-elfos, o único povo que realmente entende o que é viver entre dois mundos.",
          deslocamento: 9,
          nomeRaca: "Meio-Elfo",
          talento: null,
          tipo: "Humanoide",

          //Atribuindo Listas
          idiomas: [Comum(), Elfico()],
          nomesMasculinos: [
            "Adran",
            "Aelar",
            "Aramil",
            "Arannis",
            "Aust",
            "Beiro",
            "Berrian",
            "Carric",
            "Enialis",
            "Erdan",
            "Erevan",
            "Galinndan",
            "Hadarai",
            "Heian",
            "Himo",
            "Immeral",
            "Ivellios",
            "Laucian",
            "Mindartis",
            "Paelias",
            "Peren",
            "Quarion",
            "Riardon",
            "Rolen",
            "Soveliss",
            "Thamior",
            "Tharivol",
            "Theren",
            "Varis",
            "Aseir",
            "Bardeid",
            "Haseid",
            "Khemed",
            "Mehmen",
            "Sudeiman",
            "Zasheir",
            "Darvin",
            "Dorn",
            "Evendur",
            "Gorstag",
            "Grim",
            "Helm",
            "Malark",
            "Morn",
            "Randal",
            "Stedd",
            "Bor",
            "Fodel",
            "Glar",
            "Grigor",
            "Igan",
            "Ivor",
            "Kosef",
            "Mival",
            "Orel",
            "Pavel",
            "Sergor",
            "Ander",
            "Blath",
            "Bran",
            "Frath",
            "Geth",
            "Lander",
            "Luth",
            "Malcer",
            "Stor",
            "Taman",
            "Urth",
            "Aoth",
            "Bareris",
            "Ehput-Ki",
            "Kethoth",
            "Mumed",
            "Ramas",
            "So-Kehur",
            "Thazar-De",
            "Urhur",
            "Borivik",
            "Faurgar",
            "Jandar",
            "Kanithar",
            "Madislak",
            "Ralmevik",
            "Shaumar",
            "Vladislak",
            "An",
            "Chen",
            "Chi",
            "Fai",
            "Jiang",
            "Jun",
            "Lian",
            "Long",
            "Meng",
            "On",
            "Shan",
            "Shui",
            "Wen",
            "Anton",
            "Diero",
            "Marcon",
            "Pieron",
            "Rimardo",
            "Romero",
            "Salazar",
            "Umbero",
          ],
          nomesFemininos: [
            "Atala",
            "Ceidil",
            "Hama",
            "Jasmal",
            "Meilil",
            "Seipora",
            "Yasheira",
            "Zasheida",
            "Arveene",
            "Esvele",
            "Jhessail",
            "Kerri",
            "Lureene",
            "Miri",
            "Rowan",
            "Shandri",
            "Tessele",
            "Alethra",
            "Kara",
            "Katernin",
            "Mara",
            "Natali",
            "Olma",
            "Tana",
            "Zora",
            "Amafrey",
            "Betha",
            "Cefrey",
            "Kethra",
            "Mara",
            "Olga",
            "Silifrey",
            "Westra",
            "Arizima",
            "Chathi",
            "Nephis",
            "Nulara",
            "Murithi",
            "Sefris",
            "Thola",
            "Umara",
            "Zolis",
            "Fyevarra",
            "Hulmarra",
            "Immith",
            "Imzel",
            "Navarra",
            "Shevarra",
            "Tammith",
            "Yuldra",
            "Bai",
            "Chao",
            "Jia",
            "Lei",
            "Mei",
            "Qiao",
            "Shui",
            "Tai",
            "Balama",
            "Dona",
            "Faila",
            "Jalana",
            "Luisa",
            "Marta",
            "Quara",
            "Selise",
            "Vonda",
            "Adran",
            "Aelar",
            "Aramil",
            "Arannis",
            "Aust",
            "Beiro",
            "Berrian",
            "Carric",
            "Enialis",
            "Erdan",
            "Erevan",
            "Galinndan",
            "Hadarai",
            "Heian",
            "Himo",
            "Immeral",
            "Ivellios",
            "Laucian",
            "Mindartis",
            "Paelias",
            "Peren",
            "Quarion",
            "Riardon",
            "Rolen",
            "Soveliss",
            "Thamior",
            "Tharivol",
            "Theren",
            "Varis",
            "Adrie",
            "Althaea",
            "Anastrianna",
            "Andraste",
            "Antinua",
            "Bethrynna",
            "Birel",
            "Caelynn",
            "Drusilia",
            "Enna",
            "Felosial",
            "Ielenia",
            "Jelenneth",
            "Keyleth",
            "Leshanna",
            "Lia",
            "Meriele",
            "Mialee",
            "Naivara",
            "Quelenna",
            "Quillathe",
            "Sariel",
            "Shanairra",
            "Shava",
            "Silaqui",
            "Theirastra",
            "Thia",
            "Vadania",
            "Valanthe",
            "Xanaphia",
          ],
          pericias: [],
          proficienciasNativas: [],
          proficienciasOpcionais: [],
          sobrenomes: [
            "Basha",
            "Dumein",
            "Jassan",
            "Khalid",
            "Mostana",
            "Pashar",
            "Rein",
            "Amblecrown",
            "Buckman",
            "Dundragon",
            "Evenwood",
            "Greycastle",
            "Tallstag",
            "Bersk",
            "Chernin",
            "Dotsk",
            "Kulenov",
            "Marsk",
            "Nemetsk",
            "Shemov",
            "Starag",
            "Brightwood",
            "Helder",
            "Hornraven",
            "Lackman",
            "Stormwind",
            "Windrivver",
            "Ankhalab",
            "Anskuld",
            "Fezim",
            "Hahpet",
            "Nathandem",
            "Sepret",
            "Uuthrakt",
            "Chergoba",
            "Dyernina",
            "Iltazyara",
            "Murnyethara",
            "Stayanoga",
            "Ulmokina",
            "Chien",
            "Huang",
            "Kao",
            "Kung",
            "Lao",
            "Ling",
            "Mei",
            "Pin",
            "Shin",
            "Sum",
            "Tan",
            "Wan",
            "Agosto",
            "Astorio",
            "Calabra",
            "Domine",
            "Falone",
            "Marivaldi",
            "Pisacar",
            "Ramondo",
            "Amakiir (Joia Florida)",
            "Amastacia (Flor das Estrelas)",
            "Galanodel (Sussurro da Lua)",
            "Holimion (Orvalho dos Diamantes)",
            "Ilphelkiir (Pétala Preciosa)",
            "Liadon (Folha de Prata)",
            "Meliamne (Calcanhar de Carvalho)",
            "Nailo (Brisa da Noite)",
            "Siannodel (Córrego Lunar)",
            "Xiloscient (Pétala de Ouro)",
          ],
          tracosRaciais: [
            Habilidade(
              descricao:
                  "Seu valor de Carisma aumenta em 2 e outros dois valores de habilidade, à sua escolha, aumentam em 1.",
              nivelDesbloqueio: 0,
              nome: "Aumento no Valor de Habilidade",
            ),
            Habilidade(
              descricao:
                  "Você ganha proficiência em duas perícias, à sua escolha.",
              nivelDesbloqueio: 0,
              nome: "Versatilidade em Perícia",
            ),
            Habilidade(
              descricao:
                  "Você possui vantagem em testes de resistência contra encantamento e magia não pode colocar você pra dormir.",
              nivelDesbloqueio: 0,
              nome: "Ancestral Feérico",
            ),
            Habilidade(
              descricao:
                  "Graças ao seu sangue élfico, você tem uma visão superior no escuro e na penumbra. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra. Você não pode discernir cores no escuro, apenas tons de cinza.",
              nivelDesbloqueio: 0,
              nome: "Visão no Escuro",
            ),
          ],
          valoresHabilidade: [Carisma(valor: 2)],
        ) {
    idiomaI != null ? idiomas.add(idiomaI) : null;
    periciaI != null ? pericias.add(periciaI) : null;
    periciaII != null ? pericias.add(periciaII) : null;
    valorHabilidadeI != null ? valoresHabilidade.add(valorHabilidadeI) : null;
    valorHabilidadeII != null ? valoresHabilidade.add(valorHabilidadeII) : null;
  }

  Idioma? get idiomaI => _idiomaI;
  ValorHabilidade? get valorHabilidadeI => _valorHabilidadeI;
  ValorHabilidade? get valorHabilidadeII => _valorHabilidadeII;
  Pericia? get periciaI => _periciaI;
  Pericia? get periciaII => _periciaII;
}
