import '../../Habilidade/habilidade.dart';
import '../../Personagem/index.dart';
import '../../Idioma/index.dart';
import '../index.dart';

class Humanos extends Raca {
  Humanos()
      : super(
          //Atribuindo
          categoriaTamanho: CategoriaTamanho.Medio,
          descricao:
              "Os humanos são os mais adaptáveis, flexíveis e ambiciosos entre todas as raças comuns. Eles têm amplos e distintos gostos, moralidades e hábitos nas muitas diferentes regiões onde eles se instalaram. Quando se estabelecem em um lugar, eles permanecem: eles constroem cidades que duram por eras, e grandes reinos que podem persistir por longos séculos. Um único humano pode ter uma vida relativamente curta, mas uma nação ou cultura humana preserva tradições com origens muito além do alcance da memória de qualquer um dos humanos. Eles vivem plenamente o presente – tornandoos bem adaptados a uma vida de aventuras – mas também planejam o futuro, esforçando-se para deixar um legado duradouro. Individualmente e como grupo, os humanos são oportunistas adaptáveis, e permanecem alerta às dinâmicas mudanças políticas e sociais.",
          deslocamento: 9,
          nomeRaca: "Humano",
          talento: null,
          tipo: "Humanoide",

          //Atribuindo - Listas
          idiomas: [Comum()],
          nomesMasculinos: [
            "Aseir",
            "Bardeid",
            "Haseid",
            "Khemed",
            "Mehmen",
            "Sudeiman",
            "Zasheir",
            "Darvin",
            "Dorn",
            "Evendur",
            "Gorstag",
            "Grim",
            "Helm",
            "Malark",
            "Morn",
            "Randal",
            "Stedd",
            "Bor",
            "Fodel",
            "Glar",
            "Grigor",
            "Igan",
            "Ivor",
            "Kosef",
            "Mival",
            "Orel",
            "Pavel",
            "Sergor",
            "Ander",
            "Blath",
            "Bran",
            "Frath",
            "Geth",
            "Lander",
            "Luth",
            "Malcer",
            "Stor",
            "Taman",
            "Urth",
            "Aoth",
            "Bareris",
            "Ehput-Ki",
            "Kethoth",
            "Mumed",
            "Ramas",
            "So-Kehur",
            "Thazar-De",
            "Urhur",
            "Borivik",
            "Faurgar",
            "Jandar",
            "Kanithar",
            "Madislak",
            "Ralmevik",
            "Shaumar",
            "Vladislak",
            "An",
            "Chen",
            "Chi",
            "Fai",
            "Jiang",
            "Jun",
            "Lian",
            "Long",
            "Meng",
            "On",
            "Shan",
            "Shui",
            "Wen",
            "Anton",
            "Diero",
            "Marcon",
            "Pieron",
            "Rimardo",
            "Romero",
            "Salazar",
            "Umbero",
          ],
          nomesFemininos: [
            "Atala",
            "Ceidil",
            "Hama",
            "Jasmal",
            "Meilil",
            "Seipora",
            "Yasheira",
            "Zasheida",
            "Arveene",
            "Esvele",
            "Jhessail",
            "Kerri",
            "Lureene",
            "Miri",
            "Rowan",
            "Shandri",
            "Tessele",
            "Alethra",
            "Kara",
            "Katernin",
            "Mara",
            "Natali",
            "Olma",
            "Tana",
            "Zora",
            "Amafrey",
            "Betha",
            "Cefrey",
            "Kethra",
            "Mara",
            "Olga",
            "Silifrey",
            "Westra",
            "Arizima",
            "Chathi",
            "Nephis",
            "Nulara",
            "Murithi",
            "Sefris",
            "Thola",
            "Umara",
            "Zolis",
            "Fyevarra",
            "Hulmarra",
            "Immith",
            "Imzel",
            "Navarra",
            "Shevarra",
            "Tammith",
            "Yuldra",
            "Bai",
            "Chao",
            "Jia",
            "Lei",
            "Mei",
            "Qiao",
            "Shui",
            "Tai",
            "Balama",
            "Dona",
            "Faila",
            "Jalana",
            "Luisa",
            "Marta",
            "Quara",
            "Selise",
            "Vonda",
          ],
          pericias: [],
          proficienciasNativas: [],
          proficienciasOpcionais: [],
          sobrenomes: [
            "Basha",
            "Dumein",
            "Jassan",
            "Khalid",
            "Mostana",
            "Pashar",
            "Rein",
            "Amblecrown",
            "Buckman",
            "Dundragon",
            "Evenwood",
            "Greycastle",
            "Tallstag",
            "Bersk",
            "Chernin",
            "Dotsk",
            "Kulenov",
            "Marsk",
            "Nemetsk",
            "Shemov",
            "Starag",
            "Brightwood",
            "Helder",
            "Hornraven",
            "Lackman",
            "Stormwind",
            "Windrivver",
            "Ankhalab",
            "Anskuld",
            "Fezim",
            "Hahpet",
            "Nathandem",
            "Sepret",
            "Uuthrakt",
            "Chergoba",
            "Dyernina",
            "Iltazyara",
            "Murnyethara",
            "Stayanoga",
            "Ulmokina",
            "Chien",
            "Huang",
            "Kao",
            "Kung",
            "Lao",
            "Ling",
            "Mei",
            "Pin",
            "Shin",
            "Sum",
            "Tan",
            "Wan",
            "Agosto",
            "Astorio",
            "Calabra",
            "Domine",
            "Falone",
            "Marivaldi",
            "Pisacar",
            "Ramondo",
          ],
          tracosRaciais: [
            Habilidade(
              descricao: "",
              nivelDesbloqueio: 0,
              nome: "Aumento no Valor de Habilidade",
            ),
          ],
          valoresHabilidade: [
            Forca(valor: 1),
            Destreza(valor: 1),
            Constituicao(valor: 1),
            Inteligencia(valor: 1),
            Sabedoria(valor: 1),
            Carisma(valor: 1),
          ],
        ) {}
}
