import 'index.dart';

class ColTalentos {
  //Atributos
  List<Talento> _collection = [
    AdeptoElementalAcido(),
    AdeptoElementalEletrico(),
    AdeptoElementalFogo(),
    AdeptoElementalFrio(),
    AdeptoElementalTrovao(),
    Alerta(),
    Ambidestro(),
    AtacanteBestial(),
    AtiradorAgucado(),
    AtiradorMagia(),
    Atleta(),
    Ator(),
    CombatenteMontado(),
    ConjuradorGuerra(),
    ConjuradorRitual(),
    Curandeiro(),
    DuelistaDefensivo(),
    EspecialistaBesta(),
    EspecialistaBriga(),
    ExploradorCavernas(),
    Imobilizador(),
    IniciadoMagiaBardo(),
    IniciadoMagiaBruxo(),
    IniciadoMagiaClerigo(),
    IniciadoMagiaDruida(),
    IniciadoMagiaFeiticeiro(),
    IniciadoMagiaMago(),
    InvestidaPoderosa(),
    LiderInspirador(),
    MaestriaArmaduraMedia(),
    MaestriaArmaduraPesada(),
    MaestriaArmaHaste(),
    MatadorConjuradores(),
    MenteAfiada(),
    MestreArmasDestreza(),
    MestreArmasForca(),
    MestreArmasGrandes(),
    MestreEscudo(),
    Mobilidade(),
    ObservadorInteligencia(),
    ObservadorSabedoria(),
    Perito(),
    Poliglota(),
    ProtecaoLeve(),
    ProtecaoModerada(),
    ProtecaoPesada(),
    ResilienteCarisma(),
    ResilienteConstituicao(),
    ResilienteDestreza(),
    ResilienteForca(),
    ResilienteInteligencia(),
    ResilienteSabedoria(),
    Resistente(),
    Robusto(),
    Sentinela(),
    Sorrateiro(),
    Sortudo()
  ];

  //Modificadores de acesso
  List<Talento> get collection => _collection;
}
